import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainContent from "@/components/MainContent";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import { SessionProviders } from "@/utils/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>
          <Header />

          <main className="flex min-h-custom ">
            <MainContent>{children}</MainContent>
          </main>
          <footer></footer>
        </SessionProviders>
      </body>
    </html>
  );
}
